name: cypress
on: push
jobs:
 cypress-run:
    env:
      PORT: ${{secrets.PORT}}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          command: npm run cy:e2e